Fix/job applications zip
unepwcmc/unep-wcmc.org pull request #120
Opened 2020-11-18 17:58 UTC by stanleypliu

**Ticket**

https://unep-wcmc.codebasehq.com/projects/bits-and-bugs/tickets/39

Added an extra condition to the `download_all_applications_zip` method in the Job Applications controller which checks whether the number of folders in the generated zip file matches the number of submissions expected, and if not, regenerates the zip. I did notice that the modified time of a few of the zip files in the cache (on production) were after the `updated_at` of the last submission without including newer applications in the zip, which was odd. Couldn't pinpoint where they were being modified, so I came to the conclusion that the zip might not be regenerating when it should, hence I thought about adding another way to check whether the zip was up to date.

2020-11-18 18:00 UTC, stanleypliu commented
@lucacug Don't know how you feel about this fix - anything else that I could also look to check?

2020-11-23 16:14 UTC, lucacug requested changes

2020-11-23 16:14 UTC, lucacug commented on lib/download/generate_zip.rb
> +
While I think this might be a good idea to check mismatch, I would review the implementation. Looking at the code looks like you are considering "valid" submissions those with all the attachments present, but the user may hit the "save and edit later" button without submitting it, so I would also check the `is_submitted` flag.

2020-11-23 16:14 UTC, lucacug commented on lib/download/generate_zip.rb
> +    number_of_applications = valid_submissions.pluck(:name).map(&:downcase).uniq.count + 1
could you clarify this `+ 1` here?

2020-11-25 08:53 UTC, stanleypliu commented on lib/download/generate_zip.rb
> +    number_of_applications = valid_submissions.pluck(:name).map(&:downcase).uniq.count + 1
Basically, the generated zip file will contain a folder corresponding to each unique name (regardless of case, it just has to be unique), so duplicate submissions will be ignored. It also adds a folder called `all_submissions` as well so the total number of folders is equal to the number of unique users who have made a submissions + 1.

2020-11-25 09:23 UTC, stanleypliu commented on lib/download/generate_zip.rb
> +
Nice catch, to be fair the `all_applications_generate_zip` method already checks for the `is_submitted` flag, but I suppose it wouldn't hurt to add it in to stop it from producing false positives.

2020-11-27 17:47 UTC, lucacug requested changes

2020-11-27 17:47 UTC, lucacug commented on lib/download/generate_zip.rb
> +    number_of_entries - 1 if all_applications_folder
I think you still need to assign the variable here, I would do something like `number_of_entries -= 1`

2020-11-27 17:47 UTC, lucacug commented on app/controllers/job_applications_controller.rb
> +    if ( zip.zip_needs_regenerating? last_uploaded_submission.updated_at ||
I would add parenthesis to the arguments
`zip.zip_needs_regenerating?(last_uploaded_submission.updated_at)`, it may get confused by the operator order otherwise.
Also I think you can get rid of the outer external parenthesis wrapping the if conditions

2020-12-08 15:26 UTC, merged